/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UberPlannerRouteImport } from './routes/uber-planner'
import { Route as TierlistRouteImport } from './routes/tierlist'
import { Route as SeedFinderRouteImport } from './routes/seed-finder'
import { Route as DictionaryRouteImport } from './routes/dictionary'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const UberPlannerRoute = UberPlannerRouteImport.update({
  id: '/uber-planner',
  path: '/uber-planner',
  getParentRoute: () => rootRouteImport,
} as any)
const TierlistRoute = TierlistRouteImport.update({
  id: '/tierlist',
  path: '/tierlist',
  getParentRoute: () => rootRouteImport,
} as any)
const SeedFinderRoute = SeedFinderRouteImport.update({
  id: '/seed-finder',
  path: '/seed-finder',
  getParentRoute: () => rootRouteImport,
} as any)
const DictionaryRoute = DictionaryRouteImport.update({
  id: '/dictionary',
  path: '/dictionary',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dictionary': typeof DictionaryRoute
  '/seed-finder': typeof SeedFinderRoute
  '/tierlist': typeof TierlistRoute
  '/uber-planner': typeof UberPlannerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dictionary': typeof DictionaryRoute
  '/seed-finder': typeof SeedFinderRoute
  '/tierlist': typeof TierlistRoute
  '/uber-planner': typeof UberPlannerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dictionary': typeof DictionaryRoute
  '/seed-finder': typeof SeedFinderRoute
  '/tierlist': typeof TierlistRoute
  '/uber-planner': typeof UberPlannerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/dictionary'
    | '/seed-finder'
    | '/tierlist'
    | '/uber-planner'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/dictionary'
    | '/seed-finder'
    | '/tierlist'
    | '/uber-planner'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/dictionary'
    | '/seed-finder'
    | '/tierlist'
    | '/uber-planner'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DictionaryRoute: typeof DictionaryRoute
  SeedFinderRoute: typeof SeedFinderRoute
  TierlistRoute: typeof TierlistRoute
  UberPlannerRoute: typeof UberPlannerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/uber-planner': {
      id: '/uber-planner'
      path: '/uber-planner'
      fullPath: '/uber-planner'
      preLoaderRoute: typeof UberPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tierlist': {
      id: '/tierlist'
      path: '/tierlist'
      fullPath: '/tierlist'
      preLoaderRoute: typeof TierlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seed-finder': {
      id: '/seed-finder'
      path: '/seed-finder'
      fullPath: '/seed-finder'
      preLoaderRoute: typeof SeedFinderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dictionary': {
      id: '/dictionary'
      path: '/dictionary'
      fullPath: '/dictionary'
      preLoaderRoute: typeof DictionaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DictionaryRoute: DictionaryRoute,
  SeedFinderRoute: SeedFinderRoute,
  TierlistRoute: TierlistRoute,
  UberPlannerRoute: UberPlannerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
